/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -T small_room.glb --shadows -M -j 
Files: small_room.glb [96.2MB] > D:\Coding\react-three-fiber-course\public\models\small_room-transformed.glb [6.58MB] (93%)
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva'
import { Color } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/small_room-transformed.glb')
  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  })

  const setFocus = (event, controlName) => {
    event.stopPropagation()
    document.getElementById(`${controlName}.color`).focus()
  }

  const setColor = (material) => {
    return {
      color: {
        value: '#FFFFFF',
        onChange: (v) => {
          materials[material].color = new Color(v)
          if (materials[material].emissive) {
            materials[material].emissive = new Color(v)
          }
        }
      }
    }
  }

  const wallLightOff = useControls(
    'Wall Light - Off',
    () => setColor('Light - Turned off'),
    []
  )
  const wallLightOn = useControls(
    'Wall Light - On',
    () => setColor('Light - Turned on'),
    []
  )

  return (
    <group {...props} dispose={null} className="mainSceneGroup">
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walls.geometry}
        material={materials['Wallpaper smal flower']}
        position={[-10.142, 7.364, -0.175]}
        scale={[0.3, 7.5, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials['Floor 1 Clear']}
        position={[-0.292, 0.001, -0.297]}
        scale={[10.151, 9.85, 10.15]}
      />
      <group
        position={[-1.352, 9.096, -10.113]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.1, 3.795, 0.09]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={nodes.Cube004_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Apoio.geometry}
        material={materials['Wood.001']}
        position={[-4.454, 1.926, -3.612]}
        rotation={[Math.PI, -0.073, Math.PI]}
        scale={[0.088, 1.084, 0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hashtag.geometry}
        material={materials['Metal.001']}
        position={[-8.93, 9.233, 2.544]}
        scale={[0.086, 0.557, 0.097]}
      />
      <group
        position={[-6.589, 9.735, -9.721]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.136, 0.126, 1.136]}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onClick={(e) => setFocus(e, 'Wall Light - Off')}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials['Black Frame - wall light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials['Light - Turned off']}
        />
      </group>
      <group
        position={[-3.215, 9.735, -9.721]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.136, 0.126, 1.136]}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onClick={(e) => setFocus(e, 'Wall Light - Off')}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials['Black Frame - wall light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials['Light - Turned off']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Wood 03']}
        position={[-7.925, 3.958, -4.909]}
        scale={[1.857, 1, 4.675]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_lamp.geometry}
        material={materials['Wood.002']}
        position={[-9.103, 8.738, 1.387]}
        rotation={[0, -1.232, 0]}
        scale={[6.417, 8.931, 6.417]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-8.842, 8.566, 4.562]}
        scale={[1, 0.1, 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Glass.geometry}
        material={materials['Window Glass.003']}
        position={[-9.895, 7.364, -2.187]}
        scale={[0.3, 7.5, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Assento.geometry}
        material={materials['Wood.001']}
        position={[-4.454, 2.421, -3.612]}
        rotation={[0, 0.107, 0]}
        scale={[1.351, 0.104, 1.351]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Wood.001']}
        position={[-3.205, 4.854, -3.747]}
        rotation={[0, 0.107, 0]}
        scale={[0.138, 0.126, 1.191]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Legs.geometry}
        material={materials['Wood.001']}
        position={[-3.626, 1.164, -2.945]}
        rotation={[0, 0.107, 0]}
        scale={[0.154, 1.163, 0.154]}
      />
      <group
        position={[-8.975, 9.499, 5.421]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={7.631}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Obj3d66-395056-1-561'].geometry}
          material={materials['08 - Default']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Obj3d66-395056-1-561_1'].geometry}
          material={materials['09 - Default']}
        />
      </group>
      <group
        position={[-8.816, 9.001, 7.07]}
        rotation={[-0.009, -1.196, 0]}
        scale={7.412}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.225, 1.974, -0.327]}
        rotation={[1.558, 0.479, -1.55]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.55, 1.981, -0.36]}
        rotation={[1.566, 0.441, -1.555]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.818, 1.964, -0.349]}
        rotation={[1.563, 0.432, -1.552]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.814, 9.14, 7.031]}
        rotation={[-0.006, -1.126, 0.003]}
        scale={7.412}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.991, 1.92, -0.331]}
        rotation={[1.565, 0.418, -1.557]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.286, 1.914, -0.362]}
        rotation={[1.56, 0.461, -1.551]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.498, 1.921, -0.287]}
        rotation={[1.571, 0.003, -1.57]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.731, 8.709, 7.099]}
        rotation={[0, -0.739, 0.004]}
        scale={7.412}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.917, 1.91, -0.325]}
        rotation={[1.563, 0.425, -1.553]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.226, 1.924, -0.36]}
        rotation={[1.572, 0.319, -1.571]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.437, 1.92, -0.328]}
        rotation={[1.571, 0.003, -1.572]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.805, 8.843, 7.092]}
        rotation={[-0.007, -1.023, 0.002]}
        scale={7.412}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-6.955, 9.482, -9.721]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.136, 0.126, 1.136]}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onClick={(e) => setFocus(e, 'Wall Light - On')}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials['Black Frame - wall light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials['Light - Turned on']}
        />
      </group>
      <group
        position={[-10.335, 9.491, -9.721]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.136, 0.126, 1.136]}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onClick={(e) => setFocus(e, 'Wall Light - Off')}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials['Black Frame - wall light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials['Light - Turned off']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Wood}
        position={[-6.25, 1.1, -0.287]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.1, 1, 0.455]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Wood}
        position={[-9.774, 1.102, -0.286]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.1, 1, 0.455]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Wood}
        position={[-7.0685, 2.96, -9.56]}
        rotation={[0.432, -1.57, 90]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Wood}
        position={[-7.052, -0.015, -0.252]}
        scale={[0.665, 1, 0.387]}
      />
      <group
        position={[-9.103, 9.109, 1.386]}
        rotation={[0, -1.232, 0]}
        scale={6.776}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={materials['Wood.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_1.geometry}
          material={materials['Wood.002']}
        />
      </group>
      <group
        position={[-9.172, 9.755, 1.182]}
        rotation={[0.177, -1.136, 0.585]}
        scale={[7.004, 6.964, 6.776]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062.geometry}
          material={materials['Wood.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_1.geometry}
          material={materials['Wood.002']}
        />
      </group>
      <group
        position={[-9.042, 10.834, 1.547]}
        rotation={[0.022, -1.046, -1.002]}
        scale={[6.965, 7.03, 6.776]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064.geometry}
          material={materials['Wood.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_1.geometry}
          material={materials['Wood.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder042.geometry}
        material={materials['Material.003']}
        position={[-8.883, 11.094, 2.142]}
        rotation={[0, 0.339, Math.PI / 2]}
        scale={6.776}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={materials['Material.015']}
        position={[-8.757, 11.256, 2.443]}
        rotation={[0.184, -1.215, 0.291]}
        scale={[6.8, 6.794, 6.778]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder056.geometry}
        material={nodes.Cylinder056.material}
        position={[-8.73, 10.813, 2.488]}
        rotation={[0.184, -1.215, 0.291]}
        scale={[6.8, 6.794, 6.778]}
      />
      <group
        position={[-8.721, 10.773, 2.491]}
        rotation={[0.184, -1.218, 0.291]}
        scale={[6.792, 6.794, 6.771]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044_2.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group
        position={[-8.66, 10.174, 2.547]}
        rotation={[0.184, -1.218, 0.291]}
        scale={[0.336, 0.202, 0.327]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder055.geometry}
        material={materials['Glass.002']}
        position={[-8.694, 10.451, 2.521]}
        rotation={[0.184, -1.218, 0.291]}
        scale={[6.792, 6.794, 6.771]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-9.07, 9.981, 1.357]}
        rotation={[0, -1.232, 0]}
        scale={2.483}
      />
      <group
        position={[-7.734, 4.208, -3.735]}
        rotation={[0, Math.PI / 2, 0]}
        scale={8.121}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.MB_keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials.MB_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_3.geometry}
          material={materials['MB_metal 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_4.geometry}
          material={materials['MB_gray logo']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_5.geometry}
          material={materials.MB_desktop}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_6.geometry}
          material={materials['MB_screen black']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_7.geometry}
          material={materials['MB_plastic 01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_8.geometry}
          material={materials['MB_plastic 02']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_9.geometry}
          material={materials.MB_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_10.geometry}
          material={materials['MB_metal 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_11.geometry}
          material={materials['MB_metal 2']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed.geometry}
        material={materials.Bed}
        position={[6.39, -0.588, -4.269]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.053, 0.052, 0.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cover.geometry}
        material={materials.Bed}
        position={[6.39, -0.689, -4.269]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.053, 0.052, 0.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillows.geometry}
        material={materials.Pillows}
        position={[6.39, 1.195, -4.269]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Structure.geometry}
        material={materials.Bed_Wood}
        position={[6.39, 2.354, -4.269]}
        scale={5.249}
      />
      <group
        position={[-8.126, 1.967, -0.318]}
        rotation={[1.562, 0.482, -1.551]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.454, 1.973, -0.33]}
        rotation={[1.564, 0.444, -1.553]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.727, 1.956, -0.337]}
        rotation={[1.562, 0.431, -1.548]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.003, 1.944, -0.339]}
        rotation={[1.579, 0.554, -1.559]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.379, 1.967, -0.356]}
        rotation={[1.565, 0.443, -1.553]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.654, 1.95, -0.326]}
        rotation={[1.571, 0.439, -1.555]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.069, 1.876, -0.362]}
        rotation={[1.567, 0.372, -1.562]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.381, 1.888, -0.32]}
        rotation={[1.57, 0.005, -1.573]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.57, 1.873, -0.299]}
        rotation={[1.571, 0.003, -1.57]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-9.189, 1.982, -0.364]}
        rotation={[1.57, 0.318, -1.57]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.612, 1.964, -0.33]}
        rotation={[1.568, 0.439, -1.554]}
        scale={3.961}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
      <group
        position={[-8.875, 1.947, -0.342]}
        rotation={[1.562, 0.429, -1.549]}
        scale={3.79}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials['book cover']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['stacked paper']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/small_room-transformed.glb')
